=== patrickneubauer/ECSS/sts-example/meta-modelling/spacetransportationservice/model/spacetransportationservice-anyElement-operatorServices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:sts="http://cs.york.ac.uk/ecss/examples/spacetransportationservice" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://cs.york.ac.uk/ecss/examples/spacetransportationservice">
  <xsd:element name="Spacecraft" type="sts:Spacecraft"/>
  <xsd:element name="LaunchSite" type="sts:LaunchSite"/>
  <xsd:element name="Stage" type="sts:Stage"/>
  <xsd:element name="PhysicalProperty" type="sts:PhysicalProperty"/>
  <xsd:element name="NamedElement" type="sts:NamedElement"/>
  <xsd:element name="EngineType" type="sts:EngineType"/>
  <xsd:element name="SpaceTransportationService" type="sts:SpaceTransportationService"/>
  <xsd:complexType name="Spacecraft">
    <xsd:complexContent>
      <xsd:extension base="sts:NamedElement">
        <xsd:sequence>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="stages" type="sts:Stage"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="functions" type="sts:Function"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="physicalProperty" type="sts:PhysicalProperty"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="launchSite" type="xsd:IDREFS"/>
        </xsd:sequence>
    <xsd:attribute name="manufacturer" type="xsd:string"/>
        <xsd:attribute name="countryOfOrigin" type="xsd:string"/>
        <xsd:attribute name="relaunchCostInMioUSD" type="xsd:integer" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="LaunchSite">
    <xsd:complexContent>
      <xsd:extension base="sts:NamedElement">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="launchSiteId" type="xsd:ID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="physicalProperty" type="sts:PhysicalProperty"/>
          <xsd:element name="operator">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="operatorName" type="xsd:string"/>
                <xsd:any minOccurs="0"/>
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="locationLatitude" type="xsd:decimal" use="required"/>
        <xsd:attribute name="locationLongitude" type="xsd:decimal" use="required"/>
        <xsd:attribute name="numberOfLaunchpads" type="xsd:integer" use="required"/>
        <xsd:attribute name="operational" type="xsd:boolean" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="Stage">
    <xsd:complexContent>
      <xsd:extension base="sts:NamedElement">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="1" name="engineType" type="xsd:IDREF"/>
		  <xsd:element maxOccurs="unbounded" minOccurs="0" name="physicalProperty" type="sts:PhysicalProperty"/>
        </xsd:sequence>
        <xsd:attribute name="engineAmount" type="xsd:integer" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="PhysicalProperty">
    <xsd:attribute name="type" type="sts:PhysicalPropertyType" use="required"/>
    <xsd:attribute name="unit" type="xsd:string"/>
    <xsd:attribute name="value" type="xsd:decimal" use="required"/>
  </xsd:complexType>
  <xsd:complexType abstract="true" name="NamedElement">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
  <xsd:simpleType name="Function">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="MARS_COLONIZATION"/>
      <xsd:enumeration value="EARTH_LUNAR_TRANSPORT"/>
      <xsd:enumeration value="MULTIPLANETARY_TRANSPORT"/>
      <xsd:enumeration value="INTERCONTINENTAL_TRANSPORT"/>
      <xsd:enumeration value="ORBITAL_LAUNCHER"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="PhysicalPropertyType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="LENGTH"/>
      <xsd:enumeration value="WIDTH"/>
      <xsd:enumeration value="DIAMETER"/>
      <xsd:enumeration value="PERIMETER"/>
      <xsd:enumeration value="AREA"/>
      <xsd:enumeration value="VOLUME"/>
      <xsd:enumeration value="MASS"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="EngineType">
    <xsd:complexContent>
      <xsd:extension base="sts:NamedElement">
	      <xsd:sequence>
	     	 <xsd:element maxOccurs="1" minOccurs="1" name="engineTypeId" type="xsd:ID"/>
	      </xsd:sequence>
        <xsd:attribute name="fuelKind" type="xsd:string" use="required"/>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:complexType name="SpaceTransportationService">
    <xsd:sequence>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="launchSite" type="sts:LaunchSite"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="engineType" type="sts:EngineType"/>
      <xsd:element maxOccurs="unbounded" minOccurs="0" name="spacecraft" type="sts:Spacecraft"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== patrickneubauer/ECSS/sts-example/meta-modelling/spacetransportationservice/model/spacetransportationservice-anyElement-operatorServices.xml
<?xml version="1.0" encoding="UTF-8"?>
<sts:SpaceTransportationService
	xmlns:sts="http://cs.york.ac.uk/ecss/examples/spacetransportationservice"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cs.york.ac.uk/ecss/examples/spacetransportationservice spacetransportationservice-anyElement-operatorServices.xsd ">
	
	<launchSite locationLatitude="0.0" locationLongitude="0.0"
		name="" numberOfLaunchpads="0" operational="true">
		<launchSiteId>idvalue0</launchSiteId>
		<physicalProperty type="LENGTH" unit=""
			value="0.0" />
		<operator>
			<operatorName>NASA</operatorName>
			
		</operator>
	</launchSite>
	
	<engineType fuelKind="" name="">
		<engineTypeId>idvalue1</engineTypeId>
	</engineType>
	
	<spacecraft countryOfOrigin="" manufacturer="" name=""
		relaunchCostInMioUSD="0">
		<stages engineAmount="0" name="">
			<engineType>idvalue1</engineType>
			<physicalProperty type="LENGTH" unit=""
				value="0.0" />
		</stages>
		<functions>MARS_COLONIZATION</functions>
		<physicalProperty type="LENGTH" unit=""
			value="0.0" />
		<launchSite>idvalue0</launchSite>
	</spacecraft>
	
</sts:SpaceTransportationService>
